application: markermaker-148719
version: 1
runtime: go
api_version: go1

handlers:
- url: /bower_components
  static_dir: bower_components
  
- url: /templates
  static_dir: static/html

- url: /.*
  script: _go_app
  #login: admin
