#!/usr/bin/env bash

echo "Building linux.trackermain binary."
env GOOS=linux go build -o linux.trackermain main.go

echo "Pushing da front."
./push_front

echo "Pushing da binary."
rsync -avz -L --progress -h\
 ./linux.trackermain freya:~/track.areteh.co/

echo "Finished the pushall.
ssh freya && ./track.areteh.co/kickstart

to relauncher"
