#!/usr/bin/env bash

#account=ciy7ijqu3001a2rocq88pi8s4
account=rotblauer
access_token=pk.eyJ1Ijoicm90YmxhdWVyIiwiYSI6ImNpeTdidjZxajAwMzEycW1waGdrNmh3NmsifQ.OpXHPqEHK2sTbQ4-pmhAMQ
curl http://api.tiles.mapbox.com/v3/$account/tilesets.json?access_token=$access_token


# curl https://api.mapbox.com/v4/mapbox.light/1/0/0.png?access_token=your-access-token



